// This is an autogenerated file from running `firebase genkit:flow`.
'use server';

/**
 * @fileOverview Provides book recommendations based on user-provided mood or interest.
 *
 * - getBookRecommendations - A function that takes a mood or interest as input and returns a list of book recommendations.
 * - GetBookRecommendationsInput - The input type for the getBookRecommendations function.
 * - GetBookRecommendationsOutput - The return type for the getBookRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { validateAIInput, checkContentPolicy, ValidationError } from '@/lib/ai-validation';
import { withRateLimit } from '@/lib/rate-limiter';

const GetBookRecommendationsInputSchema = z.object({
  moodOrInterest: z
    .string()
    .min(1)
    .max(500)
    .describe('The mood or interest for which to find book recommendations.'),
  userId: z
    .string()
    .min(1)
    .describe('The user ID for rate limiting.'),
});
export type GetBookRecommendationsInput = z.infer<typeof GetBookRecommendationsInputSchema>;

const GetBookRecommendationsOutputSchema = z.object({
  recommendations: z
    .array(z.string())
    .describe('A list of book recommendations based on the provided mood or interest.'),
});
export type GetBookRecommendationsOutput = z.infer<typeof GetBookRecommendationsOutputSchema>;

export async function getBookRecommendations(input: GetBookRecommendationsInput): Promise<GetBookRecommendationsOutput> {
  try {
    // Validate input schema
    const validatedInput = GetBookRecommendationsInputSchema.parse(input);
    
    // Check content policy
    const contentCheck = checkContentPolicy(validatedInput.moodOrInterest);
    if (!contentCheck.isAcceptable) {
      throw new ValidationError(`Mood or interest contains inappropriate content: ${contentCheck.issues?.join(', ')}`);
    }

    // Apply rate limiting and generate recommendations
    return await withRateLimit(validatedInput.userId, 'ai-recommendation', async () => {
      return getBookRecommendationsFlow(validatedInput);
    });

  } catch (error) {
    console.error('Book recommendations generation error:', error);
    
    if (error instanceof ValidationError) {
      throw error;
    }
    
    if (error instanceof z.ZodError) {
      const formattedErrors = error.errors.map(err => 
        `${err.path.join('.')}: ${err.message}`
      ).join(', ');
      throw new Error(`Validation failed: ${formattedErrors}`);
    }
    
    throw new Error('Failed to generate book recommendations. Please try again.');
  }
}

const prompt = ai.definePrompt({
  name: 'getBookRecommendationsPrompt',
  input: {schema: GetBookRecommendationsInputSchema},
  output: {schema: GetBookRecommendationsOutputSchema},
  prompt: `You are a book recommendation expert. Based on the user's mood or interest, provide a list of book recommendations.

Mood or Interest: {{{moodOrInterest}}}

Provide the recommendations as a list of book titles.`,
});

const getBookRecommendationsFlow = ai.defineFlow(
  {
    name: 'getBookRecommendationsFlow',
    inputSchema: GetBookRecommendationsInputSchema,
    outputSchema: GetBookRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
