#!/usr/bin/env bash
# ╔══════════════════════════════════════════════════════════════╗
# ║   BookEX — One-Command Azure Installer                       ║
# ║                                                              ║
# ║   ZERO-PROMPT mode (paste this whole block into terminal):   ║
# ║                                                              ║
# ║   export MONGODB_URI='mongodb://bookex:PASS@127.0.0.1:27017/admin' \
# ║          NEXTAUTH_SECRET='your-secret' \
# ║          MEDIA_API_SECRET='your-secret' \
# ║          RESEND_API_KEY='re_...' \
# ║          GEMINI_API_KEY='AIza...' && \
# ║   curl -fsSL https://raw.githubusercontent.com/prof-rdx/BookEX/main/deploy/install.sh \
# ║        -o ~/install.sh && bash ~/install.sh                  ║
# ╚══════════════════════════════════════════════════════════════╝
set -euo pipefail

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
ok()   { echo -e "${GREEN}  ✔ ${NC}$*"; }
info() { echo -e "${CYAN}  ▶ ${NC}$*"; }
warn() { echo -e "${YELLOW}  ⚠ ${NC}$*"; }
fail() { echo -e "${RED}  ✖ ${NC}$*"; exit 1; }
line() { echo -e "${CYAN}──────────────────────────────────────────────────${NC}"; }

DOMAIN="bookex.farya.pk"
APP_DIR="/var/www/bookex"
REPO_URL="https://github.com/prof-rdx/BookEX.git"
CERTBOT_EMAIL="ahmednaeemx@gmail.com"
UPLOAD_ROOT="/var/www/bookex-uploads"

# ask() — works even when piped from curl
ask() {
  local prompt="$1" default="${2:-}" answer
  if [ -n "$default" ]; then
    printf "${BOLD}  %s${NC} [%s]: " "$prompt" "$default" >/dev/tty
  else
    printf "${BOLD}  %s${NC}: " "$prompt" >/dev/tty
  fi
  IFS= read -r answer </dev/tty
  printf '%s' "${answer:-$default}"
}

SERVER_IP=$(curl -s --max-time 3 ifconfig.me 2>/dev/null || echo "20.219.48.78")

echo ""
echo -e "${BOLD}${CYAN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${BOLD}${CYAN}║       BookEX — One-Command Azure Installer           ║${NC}"
echo -e "${BOLD}${CYAN}║       https://bookex.farya.pk                        ║${NC}"
echo -e "${BOLD}${CYAN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""

# ═══════════════════════════════════════════════════════════════════════
echo -e "${BOLD}${CYAN}[ STEP 1/6 ] Secrets${NC}"
line

# Use env vars if pre-set; otherwise prompt.
# This makes the script work in both zero-prompt and interactive modes.

if [ -z "${MONGODB_URI:-}" ]; then
  MONGODB_URI=$(ask "MongoDB URI  (mongodb://user:pass@127.0.0.1:27017/dbname)")
fi
[ -z "$MONGODB_URI" ] && fail "MongoDB URI is required."
ok "MONGODB_URI set"

NEXTAUTH_SECRET="${NEXTAUTH_SECRET:-$(openssl rand -hex 32)}"
ok "NEXTAUTH_SECRET ready"

MEDIA_API_SECRET="${MEDIA_API_SECRET:-$(openssl rand -hex 32)}"
ok "MEDIA_API_SECRET ready"

if [ -z "${RESEND_API_KEY:-}" ]; then
  RESEND_API_KEY=$(ask "Resend API key  (Enter to skip)" "")
fi

if [ -z "${GEMINI_API_KEY:-}" ]; then
  GEMINI_API_KEY=$(ask "Gemini API key  (Enter to skip)" "")
fi

if [ -z "${GOOGLE_CLIENT_ID:-}" ]; then
  GOOGLE_CLIENT_ID=$(ask "Google OAuth Client ID  (Enter to skip)" "")
fi
GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET:-}"
if [ -n "$GOOGLE_CLIENT_ID" ] && [ -z "$GOOGLE_CLIENT_SECRET" ]; then
  GOOGLE_CLIENT_SECRET=$(ask "Google OAuth Client Secret" "")
fi

REDIS_URL="${REDIS_URL:-}"

echo ""
ok "All secrets ready — starting installation."

# ═══════════════════════════════════════════════════════════════════════
echo ""
echo -e "${BOLD}${CYAN}[ STEP 2/6 ] System packages${NC}"
line

sudo apt-get update -qq
sudo apt-get install -y curl git nginx certbot python3-certbot-nginx ufw -qq

if node --version 2>/dev/null | grep -q "^v20"; then
  ok "Node.js already at $(node --version)"
else
  info "Installing Node.js 20..."
  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - >/dev/null 2>&1
  sudo apt-get install -y nodejs -qq
  ok "Node.js $(node --version) installed"
fi

sudo npm install -g pm2 tsx --silent >/dev/null 2>&1
ok "PM2 $(pm2 --version) + tsx installed"

# ═══════════════════════════════════════════════════════════════════════
echo ""
echo -e "${BOLD}${CYAN}[ STEP 3/6 ] Clone repo + write .env.local${NC}"
line

sudo mkdir -p "$APP_DIR"
sudo chown "$USER:$USER" "$APP_DIR"
sudo mkdir -p "$UPLOAD_ROOT"/{books,avatars,community,temp}
sudo chown -R "$USER:$USER" "$UPLOAD_ROOT"
sudo mkdir -p /var/log/pm2
sudo chown -R "$USER:$USER" /var/log/pm2

if [ -d "$APP_DIR/.git" ]; then
  info "Repo exists — pulling latest from main..."
  git -C "$APP_DIR" fetch origin -q
  git -C "$APP_DIR" checkout main -q 2>/dev/null || true
  git -C "$APP_DIR" pull origin main -q
else
  info "Cloning repository..."
  git clone "$REPO_URL" "$APP_DIR" -q
fi
ok "Repository ready at $APP_DIR"

info "Writing .env.local..."
cat > "$APP_DIR/.env.local" <<ENVEOF
# BookEX Production — generated by install.sh

MONGODB_URI=${MONGODB_URI}

NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
NEXTAUTH_URL=https://${DOMAIN}
MEDIA_API_SECRET=${MEDIA_API_SECRET}

NEXT_PUBLIC_APP_URL=https://${DOMAIN}
NEXT_PUBLIC_SOCKET_URL=https://${DOMAIN}

BOOKEX_UPLOAD_ROOT=${UPLOAD_ROOT}

RESEND_API_KEY=${RESEND_API_KEY}
GOOGLE_GENAI_API_KEY=${GEMINI_API_KEY}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
REDIS_URL=${REDIS_URL}

SOCKET_PORT=3001
MEDIA_PORT=4010
MEDIA_BIND_HOST=127.0.0.1
ENVEOF

chmod 600 "$APP_DIR/.env.local"
ok ".env.local written (mode 600)"

# ═══════════════════════════════════════════════════════════════════════
echo ""
echo -e "${BOLD}${CYAN}[ STEP 4/6 ] Build the app${NC}"
line

cd "$APP_DIR"
info "npm ci..."
npm ci --frozen-lockfile --silent
ok "Dependencies installed"

info "Building Next.js (~2 min)..."
npm run build
ok "Build complete"

# ═══════════════════════════════════════════════════════════════════════
echo ""
echo -e "${BOLD}${CYAN}[ STEP 5/6 ] Nginx + Firewall + SSL${NC}"
line

info "Installing Nginx config..."
sudo cp "$APP_DIR/deploy/nginx.conf" /etc/nginx/sites-available/bookex
sudo ln -sf /etc/nginx/sites-available/bookex /etc/nginx/sites-enabled/bookex
sudo rm -f /etc/nginx/sites-enabled/default
sudo nginx -t
sudo systemctl enable nginx -q
sudo systemctl reload nginx
ok "Nginx configured"

info "Configuring firewall..."
sudo ufw allow  22/tcp  >/dev/null   # SSH
sudo ufw allow  80/tcp  >/dev/null   # HTTP  (→ redirect to HTTPS)
sudo ufw allow 443/tcp  >/dev/null   # HTTPS
sudo ufw deny  3000/tcp >/dev/null   # Next.js  (internal only)
sudo ufw deny  3001/tcp >/dev/null   # Socket.IO (internal only)
sudo ufw deny  4010/tcp >/dev/null   # Media API (internal only)
sudo ufw deny 27017/tcp >/dev/null   # MongoDB   (internal only — never expose to internet)
sudo ufw --force enable >/dev/null
ok "Firewall active (27017 blocked from internet)"

info "Requesting Let's Encrypt SSL for $DOMAIN..."
warn "DNS must already point $DOMAIN → $SERVER_IP for this to succeed."
if sudo certbot --nginx -d "$DOMAIN" \
     --non-interactive --agree-tos -m "$CERTBOT_EMAIL" --redirect 2>&1; then
  ok "SSL certificate installed — site is HTTPS"
else
  warn "Certbot failed. Once DNS propagates, run:"
  warn "  sudo certbot --nginx -d $DOMAIN --agree-tos -m $CERTBOT_EMAIL"
fi

# ═══════════════════════════════════════════════════════════════════════
echo ""
echo -e "${BOLD}${CYAN}[ STEP 6/6 ] Start services under PM2${NC}"
line

pm2 delete all 2>/dev/null || true
pm2 start "$APP_DIR/deploy/pm2.config.js"

info "Registering PM2 as system service..."
sudo env PATH="$PATH:/usr/bin" pm2 startup systemd -u "$USER" --hp "$HOME" 2>&1 | tail -2
pm2 save
ok "PM2 will auto-start on server reboot"

# ═══════════════════════════════════════════════════════════════════════
line
echo ""
echo -e "${BOLD}${GREEN}  ✅  BookEX is live!${NC}"
echo ""
echo -e "  🌐  ${BOLD}https://${DOMAIN}${NC}"
echo ""
pm2 status
echo ""
echo -e "${YELLOW}  ── Last steps ──${NC}"
echo ""
echo "  1. Add GitHub Secrets for auto-deploy:"
echo "       github.com/prof-rdx/BookEX → Settings → Secrets → Actions"
echo "       AZURE_SSH_HOST     = ${SERVER_IP}"
echo "       AZURE_SSH_USER     = ${USER}"
echo "       AZURE_SSH_PASSWORD = <your SSH password>"
echo ""
echo "  2. Merge feat/full-audit-qa-fixes → main on GitHub."
echo "     Every future git push will auto-deploy."
echo ""
echo "  3. Change SSH password:  passwd"
echo ""
line
